### ISSUE TITLE
The big split: jupyter notebook

### ISSUE THREAD

**Issue by demianriccardi** [EntropyOrg/p5-Devel-IPerl#52] opened 2015-08-17 22:30 UTC
I'm having difficulty opening old iperl notebooks jupyter notebook after installing ipython4.  I can load and reload a new iperl notebook.

**Comment by zmughal** [comment] 2015-08-20 07:33
Do you have an example file that you can attach (a Gist would work)?

I was having issues running Jupyter, but it turned out some of my older Python modules were interfering with it.

**Comment by zmughal** [comment] 2015-08-23 01:53
I tried it with the [oldest IPerl notebook](https://gist.github.com/zmughal/d8a37222c814956aebb8) and it seems to still work. I get the following message when opening it

![selection_441](https://cloud.githubusercontent.com/assets/94489/9426544/bd1eb58e-490f-11e5-9676-8b7ee8ae0ff5.png)
and I'm running it under Jupyter notebook 4.0.4:

![selection_442](https://cloud.githubusercontent.com/assets/94489/9426545/cc238528-490f-11e5-8ac3-477317b0729b.png)

**Comment by demianriccardi** [comment] 2015-08-23 18:04
Thanks!  It wasn't too big of a deal for me.  I copied and pasted into a new notebook.  I'll try again tomorrow afternoon with running an old notebook.  The problem was that opening the old notebook would open it with the python kernel.

**Comment by zmughal** [comment] 2015-08-23 18:30
Ah, I see. The metadata in the notebook might have been wrong. Now that IPerl has moved to the kernel spec, it should not happen again for future notebooks.

Still, it might be good to get a troubleshooting guide going in case it does!

**Comment by zmughal** [comment] 2015-08-29 22:58
I'm going to close this for now since I haven't been able to reproduce it. If you come across it again, please let me know!

**Closed by zmughal** 2015-08-29 22:58 UTC
